---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

params:
  EXEC: build

inputs:
- name: git
- name: ci

outputs:
- name: deploy

run:
  path: ci/go/go_build.sh
